export const STRONG_VERBS = [
  'Analizar', 'Aplicar', 'Auditar', 'Calcular', 'Clasificar', 'Comparar', 'Comprobar', 'Consolidar',
  'Construir', 'Cuantificar', 'Definir', 'Demostrar', 'Diagnosticar', 'Diseñar', 'Documentar', 'Elaborar',
  'Ejecutar', 'Evaluar', 'Examinar', 'Estructurar', 'Establecer', 'Estimar', 'Formular', 'Generar',
  'Identificar', 'Implementar', 'Inspeccionar', 'Integrar', 'Levantar', 'Medir', 'Monitorear', 'Organizar',
  'Planificar', 'Preparar', 'Procesar', 'Programar', 'Proyectar', 'Realizar', 'Recopilar', 'Registrar',
  'Reportar', 'Revisar', 'Sistematizar', 'Supervisar', 'Verificar', 'Validar', 'Actualizar', 'Administrar',
  'Ajustar', 'Alimentar', 'Asignar', 'Caracterizar', 'Codificar', 'Depurar', 'Desagregar', 'Desarrollar',
  'Detectar', 'Determinar', 'Digitalizar', 'Disponer', 'Distribuir', 'Estandarizar', 'Formatear', 'Gestionar',
  'Graficar', 'Inventariar', 'Jerarquizar', 'Mapear', 'Optimizar', 'Ordenar', 'Priorizar', 'Radicar',
  'Reconciliar', 'Relacionar', 'Segmentar', 'Tabular', 'Trazar', 'Tramitar', 'Transcribir', 'Visualizar',
  'Contrastar', 'Corroborar', 'Inscribir', 'Notificar', 'Numerar', 'Georreferenciar', 'Calendarizar',
  'Cronometrar', 'Dimensionar', 'Presupuestar', 'Costear', 'Cotizar', 'Conciliar', 'Liquidar', 'Facturar',
  'Recaudar', 'Consignar', 'Contabilizar', 'Cotejar', 'Foliar', 'Archivar', 'Indexar', 'Catalogar', 'Custodiar',
  'Remitir', 'Responder', 'Sustentar', 'Argumentar', 'Conceptuar', 'Interpretar', 'Sintetizar', 'Pronosticar',
  'Modelar', 'Simular', 'Calibrar', 'Ensayar', 'Experimentar', 'Muestrear', 'Fiscalizar', 'Controlar',
  'Vigilar', 'Rastrear', 'Evidenciar', 'Certificar', 'Acreditar', 'Constatar', 'Aprobar', 'Rechazar',
  'Observar', 'Requerir', 'Subsanar', 'Corregir', 'Rectificar', 'Modificar', 'Reformular', 'Reestructurar',
  'Operar', 'Instalar', 'Configurar', 'Parametrizar', 'Migrar', 'Respaldar', 'Restaurar', 'Probar',
  'Desplegar', 'Publicar', 'Versionar', 'Mantener', 'Reparar', 'Prevenir', 'Mitigar', 'Resolver', 'Atender',
  'Coordinar', 'Convocar', 'Citar', 'Agendar', 'Articular', 'Vincular', 'Conectar', 'Canalizar', 'Derivar',
  'Escalar', 'Comunicar', 'Informar', 'Divulgar', 'Socializar', 'Presentar', 'Exponer', 'Capacitar', 'Orientar',
  'Asesorar', 'Instruir', 'Sensibilizar', 'Entrenar', 'Acompañar', 'Facilitar', 'Redactar', 'Escribir',
  'Diligenciar', 'Formalizar', 'Suscribir', 'Protocolizar', 'Legalizar', 'Difundir', 'Agrupar', 'Etiquetar',
  'Categorizar', 'Seleccionar', 'Filtrar', 'Localizar', 'Ubicar', 'Delimitar', 'Precisar', 'Especificar',
  'Ponderar', 'Valorar', 'Correlacionar', 'Cruzar', 'Justificar', 'Entregar', 'Producir', 'Emitir', 'Expedir',
  'Proponer', 'Plantear', 'Adoptar', 'Operacionalizar', 'Materializar', 'Instrumentar', 'Fortalecer', 'Mejorar',
  'Incrementar', 'Reducir', 'Disminuir', 'Ampliar', 'Aumentar', 'Eliminar', 'Regular', 'Homologar', 'Unificar',
  'Simplificar', 'Automatizar', 'Modernizar', 'Innovar', 'Transformar', 'Adecuar', 'Adaptar', 'Alinear', 'Sincronizar',
] as const;

export const WEAK_VERBS = [
  'Apoyar', 'Ayudar', 'Colaborar', 'Contribuir', 'Participar', 'Promover', 'Fomentar', 'Impulsar', 'Fortalecer',
  'Mejorar', 'Potenciar', 'Facilitar', 'Acompañar', 'Propender', 'Procurar', 'Buscar', 'Velar', 'Garantizar',
  'Asegurar', 'Gestionar', 'Atender', 'Manejar', 'Tratar', 'Desarrollar', 'Realizar', 'Hacer', 'Efectuar',
  'Ejecutar', 'Brindar', 'Prestar', 'Ofrecer', 'Dar', 'Tener', 'Contar', 'Disponer', 'Mantener', 'Continuar',
  'Llevar', 'Adelantar', 'Adquirir', 'Conseguir', 'Obtener', 'Lograr', 'Alcanzar', 'Cumplir', 'Responder',
  'Resolver', 'Solucionar', 'Apoyar técnicamente', 'Brindar apoyo', 'Prestar apoyo', 'Brindar acompañamiento',
  'Prestar acompañamiento', 'Realizar seguimiento', 'Hacer seguimiento', 'Dar seguimiento', 'Efectuar seguimiento',
  'Realizar apoyo', 'Brindar asesoría', 'Prestar asesoría', 'Brindar asistencia', 'Prestar asistencia',
  'Apoyar la gestión', 'Apoyar procesos', 'Apoyar actividades', 'Apoyar acciones', 'Contribuir al cumplimiento',
  'Participar activamente', 'Participar en', 'Colaborar en', 'Acompañar procesos', 'Facilitar procesos',
  'Promover acciones', 'Fomentar actividades', 'Impulsar procesos', 'Fortalecer capacidades', 'Mejorar procesos',
  'Optimizar procesos', 'Gestionar acciones', 'Atender requerimientos', 'Atender necesidades', 'Velar por',
  'Procurar el cumplimiento', 'Propender por', 'Garantizar la adecuada', 'Asegurar la correcta', 'Desarrollar acciones',
  'Desarrollar actividades', 'Desarrollar procesos', 'Realizar acciones', 'Realizar actividades', 'Efectuar acciones',
  'Efectuar actividades', 'Adelantar acciones', 'Adelantar actividades', 'Llevar a cabo', 'Hacer parte',
  'Ser responsable de', 'Estar a cargo de', 'Brindar soporte', 'Prestar soporte', 'Dar soporte',
  'Apoyar administrativamente', 'Apoyar operativamente', 'Apoyar metodológicamente', 'Acompañar técnicamente',
  'Acompañar administrativamente', 'Acompañar operativamente', 'Contribuir técnicamente', 'Contribuir administrativamente',
  'Promover el cumplimiento', 'Fomentar el cumplimiento', 'Impulsar el cumplimiento', 'Fortalecer el proceso',
  'Mejorar la gestión', 'Potenciar la gestión', 'Facilitar la gestión', 'Gestionar adecuadamente', 'Atender oportunamente',
  'Responder oportunamente', 'Cumplir oportunamente', 'Realizar oportunamente', 'Desarrollar oportunamente',
  'Apoyar oportunamente', 'Brindar oportunamente', 'Procurar oportunamente', 'Velar permanentemente',
  'Mantener actualizado', 'Mantener al día', 'Mantener informado', 'Estar pendiente', 'Hacer control',
  'Realizar control', 'Efectuar control', 'Ejercer control', 'Brindar soluciones', 'Generar soluciones',
  'Buscar soluciones', 'Dar soluciones', 'Apoyar soluciones', 'Generar valor', 'Aportar valor', 'Agregar valor',
  'Contribuir al mejoramiento', 'Contribuir al fortalecimiento', 'Contribuir al desarrollo', 'Contribuir a la gestión',
  'Contribuir al logro', 'Propiciar', 'Coadyuvar', 'Gestionar integralmente', 'Gestionar de manera adecuada',
  'Desarrollar integralmente', 'Atender integralmente', 'Apoyar integralmente', 'Coordinar acciones', 'Coordinar actividades',
  'Coordinar procesos', 'Articular esfuerzos', 'Articular acciones', 'Articular actividades', 'Articular procesos',
  'Impulsar iniciativas', 'Promover iniciativas', 'Fomentar iniciativas', 'Acompañar iniciativas', 'Apoyar iniciativas',
  'Contribuir con', 'Apoyar en lo requerido', 'Realizar lo necesario', 'Hacer lo pertinente', 'Efectuar lo correspondiente',
  'Desarrollar lo requerido', 'Atender lo solicitado', 'Cumplir con lo establecido', 'Dar cumplimiento', 'Dar trámite',
  'Brindar respuesta', 'Emitir respuesta', 'Gestionar respuesta', 'Apoyar respuesta',
] as const;
